services:
  # -----------------------------------------------------------------
  # 1. CONFIGURAÇÃO DO FRONTEND (Static Site)
  # -----------------------------------------------------------------
  - type: web
    name: meu-projeto-frontend
    env: static
    rootDir: Codigo/front-end  # <-- Ajustado para a pasta correta (C maiúsculo)

  # -----------------------------------------------------------------
  # 2. CONFIGURAÇÃO DO BACKEND (Java Spring Boot com Docker)
  # -----------------------------------------------------------------
  - type: web
    name: meu-projeto-backend
    env: docker
    rootDir: Codigo/back-end   # <-- Define a pasta do backend (C maiúsculo)
    dockerfilePath: Dockerfile  #
    envVars:
      - key: APP_FRONTEND_RESET_PASSWORD_URL
        value: https://grupo-nata.vercel.app/pages/resetarSenha.html
      - key: DATA_URL
        sync: false
      - key: DATA_USERNAME
        sync: false
      - key: DATA_PASS
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        sync: false
